services:
  web-app:
    build:
      context: ./back-end/
    ports: 
      - "8001:8000"
    volumes:
      - ./back-end/Map:/Map

    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database
    
  web:
    build:
      context: ./front-end/
    volumes:
      - ./front-end:/usr/share/nginx/html/
    ports:
     - "8060:80"
    environment:
     - NGINX_PORT=8060


  files:
    build:
      context: ./back-end/Map/images
    volumes:
      - ./back-end/Map/images:/usr/share/nginx/html/images/
    ports:
     - "8040:80"
    environment:
     - NGINX_PORT=8060

  database:
    image: postgres:17.2-alpine3.21
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
