# Generated by Django 5.1.5 on 2025-02-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_remove_comment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='answers',
            field=models.JSONField(default=list),
        ),
    ]
