# Generated by Django 5.1.6 on 2025-02-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comment_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subcom',
            field=models.BooleanField(default=False),
        ),
    ]
