# Generated by Django 5.1.5 on 2025-02-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comment_subcom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
