# Generated by Django 5.1.5 on 2025-02-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visited',
            field=models.JSONField(default=list),
        ),
    ]
