# Generated by Django 5.1.5 on 2025-02-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_alter_routes_history'),
        ('users', '0002_user_visited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='routes',
        ),
        migrations.AddField(
            model_name='user',
            name='routes',
            field=models.ManyToManyField(blank=True, null=True, related_name='author', to='routes.routes'),
        ),
    ]
