# Generated by Django 5.1.6 on 2025-02-18 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_remove_comment_owner'),
        ('routes', '0002_image_alter_routes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
    ]
