# Generated by Django 5.1.6 on 2025-02-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_remove_comment_owner'),
        ('routes', '0004_routes_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routes',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='routes',
            name='images',
        ),
        migrations.AddField(
            model_name='routes',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='comments.comment'),
        ),
        migrations.AddField(
            model_name='routes',
            name='images',
            field=models.ManyToManyField(null=True, to='routes.image'),
        ),
    ]
