# Generated by Django 5.1.5 on 2025-02-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_remove_routes_comments_remove_routes_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='history',
            field=models.JSONField(default=list, null=True),
        ),
    ]
