# Generated by Django 5.1.5 on 2025-02-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_routes_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='description',
            field=models.TextField(default='YTNE'),
        ),
        migrations.AddField(
            model_name='routes',
            name='private',
            field=models.BinaryField(default=False),
        ),
    ]
