# Generated by Django 5.1.5 on 2025-02-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_routes_description_routes_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='review',
            field=models.CharField(choices=[('bad', 'bad'), ('good', 'good'), ('unconfirmed', 'unconfirmed')], default='unconfirmed', max_length=20),
        ),
    ]
