# Generated by Django 5.1.5 on 2025-02-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_alter_routes_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routes',
            name='comments',
        ),
        migrations.AddField(
            model_name='routes',
            name='comments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
