# Generated by Django 5.1.5 on 2025-02-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_remove_routes_comments_routes_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
